#開発用 テストを行う際は下記をコメントアウトする
#spring.profiles.active=product

#テスト用 テストを行う際は下記コメントを外す
spring.profiles.active=test


spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=spring_training_user
spring.datasource.password=systemsss